### ISSUE TITLE
Setting output directory for model and logs from config file name

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#102]
Although this might become useless when using [hypertrainer](https://github.com/lemairecarl/hypertrainer/tree/master/hypertrainer) in production, wouldn't be easier to use the name of the config.yaml file to set name of output directory in [train_model.py](https://github.com/NRCan/geo-deep-learning/blob/master/train_model.py#L349)? For example, see [nyoki-mtl](https://github.com/nyoki-mtl/pytorch-segmentation/blob/master/src/train.py#L63).

During testing, this makes it easier to link output logs and model to original .yaml file and therefore remember which hyperparameters were used for each training.

**Comment by remtav** [comment]
In the same vein, wouldn't be easier to force creation of parent directories if they don't exist. This applies to:
global parameter:
  data_path: /wspace/disk01/name_of_folder_where_to_create_samples
inference parameter: 
  working_folder: /home/user/Documents/user_test1/inference

Hint of how this can be done: https://stackoverflow.com/questions/50110800/python-pathlib-make-directories-if-they-don-t-exist

**Comment by mpelchat04** [comment]
Closed with #107
