### ISSUE TITLE
Enhancement: Train without test data

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#108]
With current version of geo-deep-learning, a user cannot train without test data. A non-empty hdf5 must be created, otherwise user gets following error:

`Number of samples : {'trn': 4213, 'val': 2415, 'tst': 0}
    tst_dataloader = DataLoader(tst_dataset, batch_size=batch_size, num_workers=num_workers, shuffle=True)
  File "/wspace/disk01/conda_envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/wspace/disk01/conda_envs/py36/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0`

Nevertheless, some scenarios could occur where one wants to train without test set.

**Comment by mpelchat04** [comment]
You're absolutely right. I'll mark it as a Bug, as we should handle such scenarios. 
Thanks, @remtav.

**Comment by mpelchat04** [comment]
Fixed in #112
