### ISSUE TITLE
Preparation of 4 Band Samples (Smaller Set)

### ISSUE THREAD

**Issue by victorlazio109** [NRCan/geo-deep-learning#119]
As a developer, I would like to prepare a golden set of 4 bands data. This data-set would be persistent for training, testing and bench-marking models between all developers.

By reason of lack access to the full set we would be working on a smaller set which can be hosted on Google Drive.

**Outcome:**
Location of the Dataset hosted on google drive
CSV file containing image path , labels(gpkg) and train/val/split 

### Steps
- [ ] Connection to where the NIR is added (Charles)
- [ ] Lightning module (Charles)

**Comment by CharlesAuthier** [comment]
I think we can close this.
