### ISSUE TITLE
Config files update

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#129]
In PR #112, only config_ci_segmentation_local.yaml was updated with new "Visualisation" section. Also some parameters in inference section were added (eg. "heatmaps"), others removed. Config.yaml was not updated and needs to if users want to avoid bugs. To be solved in a near PR.

In the same vein, more and more config files are added in https://github.com/NRCan/geo-deep-learning/blob/master/conf/ throughout the recent developments. Could some be merged? Could we determine which ones are most useful depending of the scenario and inform future users on which is the best template to start with?

**Comment by victorlazio109** [comment]
Resolved!
