### ISSUE TITLE
Remove OpenCV dependency

### ISSUE THREAD

**Issue by mpelchat04** [NRCan/geo-deep-learning#142]
At installation time, OpenCV has a lot of conflictual dependencies with rasterio. fiona and scikit.   

The functions that requires opencv in our code could be replaced with similar functions from scikit.  

Plus, it's only used with [distance map](https://github.com/NRCan/geo-deep-learning/blob/ef54ead799706b726871991dcd8c9549d2450f15/utils/readers.py#L77)

**Comment by CharlesAuthier** [comment]
I think with the switch to hydra PR we can close this issue
