### ISSUE TITLE
Containerization

### ISSUE THREAD

**Issue by ymoisan** [NRCan/geo-deep-learning#143]
**Aug 12, 2020 edit** : Dorval's gpsc3 -- the next generation container-based version of HPC -- now has GPUs

Containers are needed so we can easily deploy training and inference jobs.  Docker containers are runnable on all hardware, including on the cloud.

**Comment by ymoisan** [comment]
See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Comment by remtav** [comment]
Closed with #228
