### ISSUE TITLE
As A Service - Infrastructure

### ISSUE THREAD

**Issue by ymoisan** [NRCan/geo-deep-learning#145]
This is the Epic for all aspects of GDL that relate to operations.  The ultimate goal is to provide services for 1) inference and 2) training.

See this link for setting up an [easy (?) inference service](https://docs.bentoml.org/en/latest/faq.html#how-does-bentoml-compare-to-mlflow).

**Comment by CharlesAuthier** [comment]
Can you add a description of what you mean in this?

**Comment by remtav** [comment]
This is beyond the scope of the GDL project. Will close issue and discussion may follow within the team.
