### ISSUE TITLE
Overlap between samples should be restricted to a threshold value, since train/val split is now automatic.

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#148]
When preparing samples with high overlap (ex.: >25%), the automatic train/val split creates very similar samples in both sets. The evaluation on validation set is then largely overestimated.

Automatic split was implemented here: https://github.com/NRCan/geo-deep-learning/pull/123

**Comment by victorlazio109** [comment]
Possible solution: Add warning for users also document on README.md
