### ISSUE TITLE
Save hyperparameters in checkpoint.pth

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#154]
Saving hyperparameters info as dictionary in the saved model will help preserving the training info in future uses of a given model.

Also, writing this issue probably took longer that developping the suggested enhancement.

https://pytorch.org/tutorials/beginner/saving_loading_models.html

**Comment by CharlesAuthier** [comment]
With the PR switch to hydra we head le the saving of all the parameters, but not in the pth, do we still want that?

**Comment by remtav** [comment]
> With the PR switch to hydra we head le the saving of all the parameters, but not in the pth, do we still want that?

I feel this will be useful if we want to input a checkpoint from command line at inference. The architecture in the checkpoint could overwrite the default model architecture. There may be an easy way to do this with hydra, but I haven't found it.

**Comment by CharlesAuthier** [comment]
The Idea of removing it fall into water, but in all the hyperparameters are saved in another location too, so if we wanted to get rid of it's possible.

**Comment by remtav** [comment]
For the inference pipeline, it's best to keep parameters inside the checkpoint to help override default params at inference. Needs developments related to #246
