### ISSUE TITLE
At inference, GDL shouldn't load pretrained weights if a .pth is provided to load weights from.

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#157]
At inference, our model_choice.py shouldn't load any pretrained weights (ex.: Deeplabv3 with Coco pretrained weights) if a .pth is provided.

Currently, if model is trained with pretrained weights (ie "pretrained=True" in training section)1, a pretrained model is loaded by torchvision before the weights from the user-specified .pth are loaded. This is useless and creates the unnecessary need to an internet connection during inference.

A solution would be to override "pretrained" value to "False" if a .pth is provided at inference. This should be document in the yaml (warn user of this behavior) and README.

**Comment by CharlesAuthier** [comment]
The PR switch to hydra headle this.
