### ISSUE TITLE
Benchmark: need to have per-image metrics and detailed report

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#159]
Currently, when using inference.py with ground truth files, we average metrics over all predictions made. 

It would be important to keep per-image metrics for benchmarking purposes. For example, this could help us identify if the model performs better on images from a particular ecozone, season, time of day, etc.

This shows the need for a benchmarking platform that could output a complete report on a certain model's performance.

**Comment by victorlazio109** [comment]
This has been resolved in the new Benchmarking implementation recently merged.

**Comment by CharlesAuthier** [comment]
https://smp.readthedocs.io/en/latest/metrics.html#segmentation_models_pytorch.metrics.functional.iou_score

**Comment by remtav** [comment]
This is out of scope for GDL. The only evaluation GDL will continue supporting is the one happening on tst set, at end of training.
