### ISSUE TITLE
Always write rasters as Cloud Optimized GeoTIFFs (COGs)

### ISSUE THREAD

**Issue by ymoisan** [NRCan/geo-deep-learning#176]
Even though the ultimate goal of the extraction process is to have vector features, we should write our raster predictions in COGs.  For one thing, data cube environments can be set up with services that can filter/generalize raster data on the fly.  Those services could allow for quick preview or even be used as inputs to the vectorization process.  Also, having COGs (and related STAC Items eventually) can allow people to load up the data in their favorite GIS package, where alternative post-processing activities can be tested.

**Comment by remtav** [comment]
Rasters in GDL are:
- patches, after tiling burns the input ground truth (vector)
- predictions from inference (which, in term, will be polygonized to vector)

In both cases, there's no urgent need to produce a COG for these rasters within GDL.
