### ISSUE TITLE
Repeatability: in config yaml, add git tag associated with the version of GDL being used for train

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#177]
To help with repeatability, config should contain all necessary information to repeat a training and obtain exactly the same model (if randomness in gdl is controlled, which it is not currently. Should it? Is it possible/desired with DL models?)

Minimally, yaml should contain info about which version of GDL was used to train. How to make sure the mentionned version is actually the one used? Food for thought...

Thanks @bstdenis for raising.

**Comment by bstdenis** [comment]
If you properly set all the random seed at the appropriate places in the code, a training procedure can be repeated exactly on the same machine, but there is no guarantee on another machine. In my opinion, the main issue is more with having a piece of code that actually works for an old experiment. As the system evolves (change version) it is possible that old experiments will become broken with the new code, so keeping a link (tag, github hash, etc.) of the version is good practice. If it's an experiment that uses work-in-progress code, it's still a good idea to at least push it in a development branch and we can then link it with its commit hash value.

**Comment by ymoisan** [comment]
Folks, this should be taken care of in the metadata of the model, to be stored eventually in a STAC extension.  The CRIM has begun laying out a proposal for a new STAC extension for Deep Learning Models (DLM).  The hash code of a particular model instanciation is [here](https://github.com/crim-ca/CCCOT03/blob/cebb8153a041bb08b3663e15eaf6467c1d2b954b/extension/dl-model/json-schema/schema.json#L90).  We expect to propose the extension to STAC more formally in the coming weeks.
