### ISSUE TITLE
Inference: run inference without yaml

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#183]
If #154 is covered, then we can easily adapt inference.py to run without a yaml. We could think of 2 mandatory arguments:
1. image url (local path or from web)
2. model url (local path or from web to checkpoint.pth.tar)

There could also be a third, optional argument:
- number of gpus. 

If this third argument is optional though, we'd have to determine what the default behavior is:
- if multiple gpus are available, run on one gpu only?
- if multiple gpus are available, run on all available gpus? This implies that #182 would be solved.

**Comment by ymoisan** [comment]
Run inference without a YAML with two arguments as specified above is a must for Inference As A Service.  When clients (web app, QGIS plugin, notebook, etc.) will allow users to select their area of interest for inference, we will need the capacity to send the user selected BBOX to a service that will allow us to fetch just the part of data needed.  Until we can bring the inference process over onto the clients (e.g. QGIS plugin with a user that has a GPU on their machine).

**Comment by remtav** [comment]
This feature was partly broken with PR #208. 

In inference mode, if state_dict is provided from command line, GDL should set architecture accordingly (i.e. overwrite default architecture and issue warning). For example, the following command should work and will facilitate the implementation of multi-model inference #245 :

`python GDL.py mode=inference inference.state_dict_path="/path/to/custom_checkpoint.pth.tar"`
