### ISSUE TITLE
config_template.yaml: default values should lead to good baseline model

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#189]
Config_template should reflect a "generally-good-to-start-with" configuration, that is, trying to cover common use cases of GDL and output an "ok" model to start with. For example, we could set batch size=4, num_gpus=1, num_epoch=50, architecture to a simple pretrained unet that has been giving good results for us (@victorlazio109 which one?), etc.

This issue has been raised by @bstdenis. Don't hesitate to comment Mr. St-Denis!

**Comment by CharlesAuthier** [comment]
Not agree, I think that the `config_tamplate.yaml` should only be a exemple that work out of the box on any computer (so no GPU and small batch size) and see that everything is running (so small amount of epochs). One think that we can do is a `config_unet.yaml` that include what you want plus adding the weights of a unet trained in a folder. In the doc we can talk about it show some stats and saying the minimum required to train/run the unet.

**Comment by CharlesAuthier** [comment]
This could be close after the PR switch to hydra.
