### ISSUE TITLE
ignore_index parameter should be in "global" section, not "training"

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#194]
"ignore_index" parameter is used both in images_to_samples.py and train_segmentation.py
in images_to_samples, [the pixels in label corresponding to a nodata region of imagery are to set to ignore_index value](https://github.com/NRCan/geo-deep-learning/blob/9ba98c88e219b502e5431f28197fdfc4dac8718f/images_to_samples.py#L453)

in train_segmentation.py, for losses that implement it, loss is not calculated for pixels where ignore_index is found.

Also, "ignore_index" is also called "dontcare" in different parts of the code. There should be only one name for this parameter (in yaml and code)

**Comment by mpelchat04** [comment]
Is this still relevant after the hydra implementation #208 ?

**Comment by remtav** [comment]
PR #208 closes this issue
