### ISSUE TITLE
normalization parameters should be in global section of yaml, not training

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#198]
https://github.com/NRCan/geo-deep-learning/blob/4b882c3f46e3353e5d27f5929acf823c0c25b425/utils/augmentation.py#L88

The following parameters are used during training, but is also at inference. Therefore, they should be in global parameter section:
- normalization: mean & std

**Comment by mpelchat04** [comment]
Is this still relevant after the hydra implementation #208 ?

**Comment by remtav** [comment]
PR #208 closes this issue.
