### ISSUE TITLE
Deep learning applied to lidar point cloud classification

### ISSUE THREAD

**Issue by ymoisan** [NRCan/geo-deep-learning#2]
# Context

Classification of lidar [point clouds](https://en.wikipedia.org/wiki/Point_cloud) is resource-intensive as it generally involves human interaction to obtain decent results.  Furthermore, it has been shown that classification results and accuracies vary between data producers.  Finally, classification amounts to about 30% of lidar data acquisition costs.  

Given that context, how can Deep Learning (DL) help in the classification process ?

# Issues

DL architectures used in imagery are mostly [CNNs](https://en.wikipedia.org/wiki/Convolutional_neural_network).  Convolution implies pixels.  However, lidar cloud points do **not** correspond to pixels and therefore CNNs are likely not applicable in this case.

# Thoughts

Could we use prior data (DEM, imagery, etc.) to initialize weights in a scene-specific rough manner rather than using a random initialization ?

Could we use standard unsupervised clustering algorithms like [K-Means or DBSCAN](http://scikit-learn.org/stable/modules/clustering.html) ?  If so, what is the minimum number of points we can run clustering algorithms against ?

# References & projects

[Classifying airborne LiDAR point clouds via deep features learned by a multi-scale convolutional neural network](https://www.tandfonline.com/doi/abs/10.1080/13658816.2018.1431840?src=recsys&journalCode=tgis20&)  Paywalled, unfortunately ...

[Deep Semantic Classification for 3D LiDAR Data](https://arxiv.org/abs/1706.08355).  Key to using CNNs with point clouds: "The input to our network is a set of three channel 2D images generated by unwrapping 360^^0 3D LiDAR data onto a spherical 2D plane".

[PyLidar](http://www.pylidar.org/en/latest/); based on not well-known libraries ([SPDLibb[(http://www.spdlib.org/)), but developed by a government organization (New South Wales, Australia) and still looks pretty interesting: "Supported formats are: SPD V3, SPD V4, Riegl RXP, LAS, LVIS, ASCII and Pulsewaves"

[Deep learning-based tree classification using mobile LiDAR data](https://www.tandfonline.com/doi/abs/10.1080/2150704X.2015.1088668)

[Deep Semantic Classification for 3D LiDAR Data](https://arxiv.org/abs/1706.08355).  Key to using CNNs with point clouds:  "The input to our network is a set of three channel 2D images generated by unwrapping 360^^0 3D LiDAR data onto a spherical 2D plane"

[PointNet](https://github.com/charlesq34/pointnet) : "Deep Learning on Point Sets for 3D Classification and Segmentation" and it's based on [this work](https://arxiv.org/abs/1612.00593) from stanford University.

**Comment by mpelchat04** [comment]
Hi @ali-robot,  
The goal is to be able to apply DL to any pointcloud, regardless of the sensor.  At this point, we only started with a literature review to figure the best way to add this feature to Geo-deep-learning. 
That being said, our main concern is to apply this to aerial LiDAR, mainly for cartographic purposes.

**Comment by mpelchat04** [comment]
Some other infos were in a duplicate ticket: #69

**Comment by victorlazio109** [comment]
Independent project, not related to GDL.
