### ISSUE TITLE
Images_to_samples.py (hdf5s) --> data_to_tiles.py: add gdal library in conda

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#216]
Onboarding solaris requires GDL to use gdal as a python library (not just from the OS). This will require us to update environment.yml to create a functional conda env with this new dependency.
For context, see #215

**Comment by ymoisan** [comment]
I gather we'll keep using rasterio right ?  If so, we should investigate how to better use rasterio's gdal bindings and avoid [potential issues](https://rasterio.readthedocs.io/en/latest/topics/switch.html#mutual-incompatibilities).

**Comment by remtav** [comment]
> I gather we'll keep using rasterio right ? If so, we should investigate how to better use rasterio's gdal bindings and avoid [potential issues](https://rasterio.readthedocs.io/en/latest/topics/switch.html#mutual-incompatibilities).

Thank for raising this flag. Digging deeper into the solaris utilities that will be necessary for us, we can easily remove gdal as a python dependency. Solaris basically implemented the use of gdal datasets side by side with rasterio dataset. 2 examples (only 2 scripts use `from osgeo import gdal`: 
https://github.com/remtav/geo-deep-learning/blob/solaris_tiling/solaris_gdl/raster/image.py#L31
https://github.com/remtav/geo-deep-learning/blob/solaris_tiling/solaris_gdl/utils/geo.py#L151

If we decide to remove all implementations of gdal.dataset, etc., we can remove gdal as a dependency and close this issue.

**Comment by remtav** [comment]
Solaris v0.5 will [drop the gdal dependency](https://github.com/CosmiQ/solaris/issues/439).
