### ISSUE TITLE
Csv as input for sampling and inference: format needs update

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#221]
STAC items are coming GDL's way and it's time to consider deprecating csv as input in favor of a STAC item, json-like, input. Jsons may not be as friendly if a user needs to create a custom list of images to input, but a simple utility could be used to convert a csv to the json expected as input.

**Comment by remtav** [comment]
> french or English the attribute field?

This is just an example. The "attribute field" column (and all other columns actually) would accept any utf-8 character.

**Comment by remtav** [comment]
> french or English the attribute field?

This is just an example. It could be any string

**Comment by mpelchat04** [comment]
I think it's a fair assumption to "define an attribute name and value to use to filter all ground truth data [in the dataset config](https://github.com/NRCan/geo-deep-learning/blob/develop/config/dataset/test_ci_segmentation_binary.yaml#L16)". W would then remove the `attribute field` and the `attribute values` from the csv.
