### ISSUE TITLE
Reading single-band rasters: unified approach with multiband reader

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#223]
As operationalization approaches, inference.py will need to read and concatenate single band rasters rather than [multiband only](https://github.com/NRCan/geo-deep-learning/blob/develop/inference.py#L120). This implies extending [sample_creation.py](https://github.com/NRCan/geo-deep-learning/blob/develop/sample_creation.py)'s use to inference.py and possibly merging with [images_to_samples.py](https://github.com/NRCan/geo-deep-learning/blob/develop/images_to_samples.py) (soon to become data_to_tiles.py --> #215 ). 

This issue is closely related to #221 and #222. A future reading utility will have to manage a list of rasters as input with variable configration (some may be multiband, others will be single-band, maybe even for a same training dataset). This utility will then be available for tiling as well as inference.

**Comment by ymoisan** [comment]
With single-band COGs, it may be possible to use dynamic capabilities (e.g. NRCan's datacube) to create streamable (i.e. cloud optimized) multiband images ready for training or inference.  GDL would then be presented with ready-to-use N-band images for sample creation/tiling.

This ticket is about N bands of one image.  The wider use case of N-band fused data (e.g. lidar resampled to an image gsd and used in conjunction with it for training) may be better addressed with a ready-to-use N-band image generation pre-processing step.

**Comment by remtav** [comment]
This issue is becoming a priority to address as the temporary [sample_creation.py](https://github.com/NRCan/geo-deep-learning/blob/develop/sample_creation.py) for tiling single-band imagery is getting more and more outdated.

Here's what I'd suggest to make a uniform tiling pipeline for both single-band ([stac item](https://github.com/NRCan/geo-deep-learning/issues/222) or not) and multi-band imagery. In the [proposed input csv ](https://github.com/NRCan/geo-deep-learning/issues/221#issuecomment-1121310523), the imagery path could be in one of three formats:
1. path to a multi-band image file:
`my_dir/my_multiband_geofile.tif`

2. path to a single-band image file, where the band specific string in the file name would be in a hydra-like [interpolation format](https://hydra.cc/docs/1.0/advanced/override_grammar/basic/#primitives). The interpolation string would refer to a dataset parameter with a list of desired band names or strings to help resolve the single-band filenames. For example:
in dataset config:
`dataset.bands: [R, G, B]`
in input csv:
`my_dir/my_singleband_geofile_band_${dataset.bands}.tif`
The tiling script would therefore combine, in the same order as bands appear in dataset config, the following files:
`my_dir/my_singleband_geofile_band_R.tif`
`my_dir/my_singleband_geofile_band_G.tif`
`my_dir/my_singleband_geofile_band_B.tif`

3.  a stac item referring to singleband assets. Bands would be selected by [common name in dataset config](https://github.com/remtav/geo-deep-learning/blob/222-stac-item-input/config/dataset/ccmeo_datacube_dataset.yaml#L13):
`https://datacube-stage.services.geo.ca/api/collections/spacenet-samples/items/SpaceNet_AOI_2_Las_Vegas-056155973080_01_P001-WV03`

FYI, issues would be tackled in the following order: #221 , #222 , #215, #300 
This would also close the following issues: #139, #167

**Comment by valhassan** [comment]
I think the suggested solution works!
