### ISSUE TITLE
Inference.py: implement resampling of input raster

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#224]
For certain applications like building footprints, it helps to upsample an input raster to a smaller spatial resolution (ex.: 50 cm to 25 cm) in order to get a finer extraction.

This [will be implemented in the coming data_to_tiles.py](https://github.com/remtav/geo-deep-learning/blob/solaris_tiling/solaris_gdl/tile/raster_tile.py#L365), but will also be needed during inference to produce similar results on new images.

**Comment by ymoisan** [comment]
Seems to me the phrase "will also be needed during inference" comes up in several tickets.  I think we are close to the point of viewing the inference task as more than providing a runtime for [inference.py](https://github.com/NRCan/geo-deep-learning/blob/develop/inference.py).  What we really want I believe is a sound model deployment infrastructure, as per https://pytorch.org/tutorials/intermediate/flask_rest_api_tutorial.html.

**Comment by remtav** [comment]
Turned out not to be relevant.
