### ISSUE TITLE
Figures, publications, illustrations of results?

### ISSUE THREAD

**Issue by mkutu** [NRCan/geo-deep-learning#230]
Do you all have any figures, list of publications, or illustrations that I could show as I recommend this tool to others?

**Comment by CharlesAuthier** [comment]
@mpelchat04

**Comment by mkutu** [comment]
@CharlesAuthier @remtav, @mpelchat04 following up on this. A couple of options?

Government of Canada, Natural Resources Canada. Geo-deep-learning, (2019), GitHub repository, https://github.com/NRCan/geo-deep-learning

or 

Tavon R. et al. (2019) Geo-deep-learning, (2019), GitHub repository, Government of Canada, Natural Resources Canada, https://github.com/NRCan/geo-deep-learning 

Apologies if I'm assigning the wrong person as first author on the second example. I'm going by the number of commits and presuming @remtav is lead on this project. 

If I don't hear back soon I'll go with the first to play it safe.

**Comment by mpelchat04** [comment]
Citation should be as follow: 
Natural Resources Canada, Government of Canada, Geo-deep-learning, (2018), GitHub repository, https://github.com/NRCan/geo-deep-learning
