### ISSUE TITLE
WIP : Docker image optimizations

### ISSUE THREAD

**Issue by ymoisan** [NRCan/geo-deep-learning#258]
- [ ] [Copying CONDA_DIR from stage 1](https://github.com/NRCan/geo-deep-learning/blob/37cd99dc016df873ef363a1092e41e01b50eff42/Dockerfile#L73) takes more than 10 GB of temporary disk space; investigate
- [x] Build using our GitHub repo as (remote) context
  `docker build https://github....git#branch|tag|remote_referencer:optional_dir` ¹
- [ ] Create a `.dockerignore` file (aka don't ship unnecessary files to the build context)
- [ ] Build a "swiss-army knife" dockerfile to "make sure that you, your team, and the CI are all using the same environment" ²

¹ Build from a url instead of a local context; when the URL parameter points to the location of a Git repository, the repository acts as the build context. The system recursively fetches the repository and its submodules. The commit history is **not preserved.** [docker build](https://docs.docker.com/engine/reference/commandline/build/)
² [Containerize Your Go Developer Environement](https://www.docker.com/blog/tag/go-env-series/), [part 2](https://www.docker.com/blog/containerize-your-go-developer-environment-part-2/)

**Comment by remtav** [comment]
Some efforts has been put into reducing docker image size. Using Nvidia's docker image as build image is the main constraint to reducing size. CI is currently working with conda, could be using docker, but not a priority.
