### ISSUE TITLE
Reimplement classification task

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#260]
In current version of GDL, the only task available is [segmentation](https://github.com/NRCan/geo-deep-learning/blob/develop/config/task/segmentation.yaml)

PR #208 removed [train_classification](https://github.com/NRCan/geo-deep-learning/pull/208/files#diff-e949dabb684fb3241e7636304e7931e800a9bed11e9a767e27d6d38da2e19b91) and classification at inference [remains implemented in inference_segmentation.py](https://github.com/NRCan/geo-deep-learning/blob/develop/inference_segmentation.py#L612), but is unreachable due to the current usage of GDL.py using [mode and task to execute a specific script](https://github.com/NRCan/geo-deep-learning/blob/develop/config/task/segmentation.yaml#L2).

**Comment by mpelchat04** [comment]
The issue name suggest we should reimplement it but since it has been deprecated, shouldn't we just make sure it has been removed properly (i.e. in every files)?

**Comment by CharlesAuthier** [comment]
yeah I think we can only remove it
