### ISSUE TITLE
CI: shrink inference data

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#264]
[Currents CI testing](https://github.com/NRCan/geo-deep-learning/runs/5058568329?check_suite_focus=true) take 15 minutes, but 11 minutes are dedicated to inference on 2 massachusetts' dataset images. 

This is outrageously long for CI tests considering it doesn't add any value to the testing: we know after a minute or so that inference works.

**Comment by CharlesAuthier** [comment]
good idea maybe change the number of images for inference like a small 512 by 512
