### ISSUE TITLE
Implement STAC ml-model extension

### ISSUE THREAD

**Issue by ymoisan** [NRCan/geo-deep-learning#279]
Describe DL model characteristics -- e.g. metadata like what data we used for training, feature types that can be extracted -- using the emerging [STAC ml-model extension](https://github.com/stac-extensions/ml-model).
- [ ] Help define a stable/usable (tagged) version of ml-model [work with the community]
- [ ] Implement STAC model item generation in GDL following a specific version of ml-model

Once we have that we can think of implementing business logic to suggest models to a user as a function of image and features wanted for extraction.

**Comment by mpelchat04** [comment]
Out of scope for GDL. See here for this implementation: github.com/stac-extensions/ml-model
