### ISSUE TITLE
Sampling (tiling): remove "clip raster by ground truth bounds" feature

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#311]
This feature should be removed in favor of a data validation step to check, for example: 
- do the raster's bounds and ground truth's bounds intersect?
- do they overlap above a certain threshold? 

The exact overlap could be written in a data report (see #310). The user could then assess the overlap % percentage between imagery and ground truth and proceed to necessary verification. Geo-deep-learning wouldn't be automating this "clipping" anymore, mostly because the ground truth's bound (i.e. entire bounds for which the gt's data has been acquired) cannot be precisely measured. It can only be derived from bounds of all features, which is often smaller than actual bounds.

**Comment by valhassan** [comment]
> @valhassan I'd like to have your opinion on this as you've been using this feature a lot.
 
Thanks, Remi!, will this function be taken care of with the AOI object? 
This is a function that asserts the image with the bounds of the label(gpkg); (1:1) it is neccessary for training and also evaluation as coupled within inference.

**Comment by remtav** [comment]
The AOI object validates that the bounds of image and geopackage intersect, but doesn't check if they are 1:1. Actually, the bounds of a vector file is measured by the "envelope" that contains all vector features. Therefore, there is never a 1:1 fit with the image unless features extend all the way to the limits of the image. The best alternative I can find to the current approach is to check how much overlap there is between the bounds of image and label and saving this info into a report for the user to check and perform manual validation if needed.

On top of that, our upcoming pipeline will generate gpkg files on the fly for a given image and a perfect fit will be ensured.
