### ISSUE TITLE
pynvml error 

### ISSUE THREAD

**Issue by valhassan** [NRCan/geo-deep-learning#350]
![image](https://user-images.githubusercontent.com/24499815/193706942-96235d09-9532-456f-9db3-18c6d1245986.png)

Pynvml dependency is used in torch an error arises in a new environment without pynvml installed

_Originally posted by @valhassan in https://github.com/NRCan/geo-deep-learning/pull/344#discussion_r986328985_

**Comment by remtav** [comment]
Same here with a new environment...
![image](https://user-images.githubusercontent.com/34774759/193842821-f8c60bb7-21a8-40b9-abf1-0262534b5c85.png)

Torch version:
pytorch                   1.12.1          py3.10_cuda11.6_cudnn8.3.2_0    pytorch
