### ISSUE TITLE
[feature request] raster enhancement: add CLAHE enhancement option to AOI

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#359]
Our worldview images generally have a histogram skewed toward lower values, with a low contrast. Latest tests by @valhassan show that a light enhancement with the CLAHE algorithm applied on the entire image helps improve extraction for waterbodies and forests.

Although ideally enhancement would be applied dynamically during training or inference, neither [Kornia's](https://kornia.readthedocs.io/en/latest/enhance.html#kornia.enhance.equalize_clahe) nor [Scikitlearn's](https://scikit-image.org/docs/dev/api/skimage.exposure.html#equalize-adapthist) CLAHE enhancement support feeding a histogram of full image to determine the enhancement applied to a single patch. If enhancement is applied only patch by patch (which would be the easiest solution), results actually degrade compared to no enhancement at all.

Suggested implementation: 
- for training: use Kornia's CLAHE, applied to entire image, save copy of enhanced image to disk, then use this copy for tiling. 
- for inference: IDEM, but enhanced copy is read window by window.

**Comment by remtav** [comment]
I compared the CLAHE algorithm performances between [Kornia's](https://kornia.readthedocs.io/en/v0.5.0/enhance.html?highlight=clahe#kornia.enhance.equalize_clahe) and [Sklearn's](https://scikit-image.org/docs/stable/api/skimage.exposure.html#skimage.exposure.equalize_adapthist) implementation on 3 RGB images of varying sizes. 

Notes:
- Kornia's transforms expect tensor as inputs, not numpy arrays
- Sklearn expects single-band numpy arrays. The processing of a multiband array is therefore done with a for loop, processing one band at a time and concatenating results back into a multiband array.

Images:
sensor | image | height | width
-- | -- | -- | --
Aerial | NB_23322E759967N_clipped | 341 | 280
Worldview-2 | MB13-052686355070_01_P002 | 8924 | 4344
Worldview-2 | BC6P002-052652307020_01_P002 | 18424 | 9720

Here are the results:
kornia (seconds) | sklearn (seconds) | ratio_kor/sk | kornia (GiB RAM) | sklearn (GiB RAM)
-- | -- | -- | -- | --
0,0153 | 0,0362 | 0,4226519337 | 4.770 | 4.770
2,5274 | 12,2365 | 0,2065459895 | 11.132 | 6.645
12,3797 | 53,0898 | 0,2331841521 | 33.025 | 13.19

Kornia's implementation is therefore considerably faster (approx. 4 times faster), but uses more memory since the array can be processed all at once.

References:
Memory profiler: https://pythonspeed.com/fil

***
Script to reproduce:
```
import time
from pathlib import Path

import numpy as np
import rasterio
from kornia import tensor_to_image, image_to_tensor
from kornia.enhance import equalize_clahe
from rasterio.plot import reshape_as_image, reshape_as_raster
from skimage import exposure

from utils.geoutils import create_new_raster_from_base

# input params and files
enhance_clip_limit = 0.5
clip_lim_str = str(enhance_clip_limit).replace('.', '')
# 3 images to test, one by one
raster_fp = "/media/data/ccmeo_raster/benchmark/23322E759967N_clipped_1m_1of2.tif"
#raster_fp = "/media/data/ccmeo_raster/benchmark/MB13-052686355070_01_P002-WV02_red-green-blue.tif"
#raster_fp = "/media/data/ccmeo_raster/benchmark/BC6P002-052652307020_01_P002-WV02_red-green-blue.tif"

# open and read as numpy array
raster = rasterio.open(raster_fp)
raster_np = reshape_as_image(raster.read())  # channels last

### KORNIA #############################################################################################################
tic = time.perf_counter()
raster_name_clahe = Path(raster_fp).parent / f"{Path(raster_fp).stem}_clahe{clip_lim_str}_kor.tif"
raster_torch = image_to_tensor(raster_np)
raster_torch = raster_torch.float() / 255
raster_torch = equalize_clahe(raster_torch)
raster_np = tensor_to_image((raster_torch*255).long())
toc = time.perf_counter()
print(f"Kornia equalized in {toc - tic:0.4f} seconds")
########################################################################################################################

### SKLEARN ############################################################################################################
tic = time.perf_counter()
raster_name_clahe = Path(raster_fp).parent / f"{Path(raster_fp).stem}_clahe{clip_lim_str}_sk.tif"

# must process one band at the time
raster_np_enh = np.empty(raster_np.shape, dtype=raster_np.dtype)
for band_idx in range(raster_np.shape[-1]):
    band = raster_np[:, :, band_idx]
    band_enhanced = exposure.equalize_adapthist(band, clip_limit=enhance_clip_limit)
    # adapthist returns a float64 with range [0,1]
    band_enhanced = exposure.rescale_intensity(band_enhanced, out_range=(0, 255)).astype(np.uint8)
    raster_np_enh[:, :, band_idx] = band_enhanced
raster_np = raster_np_enh
toc = time.perf_counter()
print(f"Sklearn equalized in {toc - tic:0.4f} seconds")
########################################################################################################################

raster_np = reshape_as_raster(raster_np)   # channels first
create_new_raster_from_base(raster, raster_name_clahe, raster_np)
```

**Comment by ms888ekb** [comment]
I think one RTX A6000 would be a great workstation for kornia

**Comment by remtav** [comment]
As a side note, resulting images vary slightly between Kornia and Sklearn:

Sklearn:
![ksnip_20221025-132837](https://user-images.githubusercontent.com/34774759/197867246-2511baf8-629a-4c17-859a-fcd8ddcca67b.png)

Kornia (slightly "bluer" in waterbody):
![ksnip_20221025-132840](https://user-images.githubusercontent.com/34774759/197867252-fe1bf56f-9829-4faa-b78c-63d538af5dd7.png)

**Comment by remtav** [comment]
> The difference may be due to the clip_limit
> 
> * the clip_limit as implemented on scikit-image does not map to kornia's
> * looking at the code above for reproducibility; assuming it was used to create the visualizations it does not seem like the clip_limit param for Kornia was passed and it might be using a default value.

Thanks for this insight. You're right, in the script above, the default value for Kornia's clip_limit is used, which is a mistake. It should've used the "clip_limit=enhance_clip_limit". I'll edit. Also, as you've mentionned, clip_limit=0.1 for sklearn is pretty equal to clip_limit=20 with Kornia. I seem to get even closer results with 0.1 --> 25. This "translation" seems linear, i.e. 0.5 --> 125 gives identical results as well. 

In this PR, we should raise an error if 0 < clip_limit < 1, since the user may be mistaking sklearn's values with Kornia's expected values.

Thanks again @valhassan for this insight.
