### ISSUE TITLE
problems with VRT Dataset Output  

### ISSUE THREAD

**Issue by valhassan** [NRCan/geo-deep-learning#362]
Multiband VRT data is created and returned as a raster input (String XML) this is a departure from the previous functionality in which a raster file is opened as a rasterio object with properties such as (.name, .count, .meta). We are unable to use similar properties from a VRT dataset hence the output is misinterpreted and gives rise to a variety of problems.
![VRT_name_error_1](https://user-images.githubusercontent.com/24499815/194619020-411985c0-e0a7-45dd-bd7e-49d29e2b8508.PNG)
![VRT_name_error](https://user-images.githubusercontent.com/24499815/194619084-cb7dc648-af88-4ec5-b5bf-d1356df3cac8.PNG)

**Comment by remtav** [comment]
Can you detail the problems you are facing? The naming of output patches is very ugly, I agree, (­</VRTDataset......>) but hasn't been too problematic to me for now. Are you facing other problems?
