### ISSUE TITLE
Add samples to an already existing hdf5 file

### ISSUE THREAD

**Issue by mpelchat04** [NRCan/geo-deep-learning#38]
# Issue
When having large dataset to prepare, it can become quite time consuming. If you have new data to add to  your dataset, you don't want to prepare it all over again, from scratch.  

# Considerations  
- path to hdf5 files as parameter in config.yaml
- Validation for the size of the samples already in the hdf5 (height, width and number of channels)
- Final hdfs must have all samples in random order

**Comment by CharlesAuthier** [comment]
https://arxiv.org/pdf/2012.14115v1.pdf

**Comment by remtav** [comment]
With the upcoming switch to plain .tif and .geojson tiles (see issue #215 ), this is no longer relevant. HDF5 will no longer be used.
