### ISSUE TITLE
Multiclass loss calculation fails at evaluation

### ISSUE THREAD

**Issue by valhassan** [NRCan/geo-deep-learning#398]
[Evaluation] We need to correctly format the data before passing it into the multiclass loss function. 
To fix:
We can replicate this line
https://github.com/NRCan/geo-deep-learning/blob/8678cd900f12d2ded72395131b804c3babd74474/train_segmentation.py#L353
here:
https://github.com/NRCan/geo-deep-learning/blob/8678cd900f12d2ded72395131b804c3babd74474/train_segmentation.py#L445

**Comment by ms888ekb** [comment]
Hi Vic, I've tested this case and haven't noticed any difference between the values in the first and second implementation:
![loss_2022-12-13 13_25_30-Window](https://user-images.githubusercontent.com/54916039/207415762-b38ada1c-faef-411a-9839-792248b86fc6.png)

**Comment by valhassan** [comment]
Fixed with PR #496
