### ISSUE TITLE
Handling exceptions

### ISSUE THREAD

**Issue by ymoisan** [NRCan/geo-deep-learning#4]
Add Try blocks to the code to handle exceptions where needed.  

Interesting references:  
https://www.pythonforthelab.com/blog/learning-not-to-handle-exceptions/  
https://www.tutorialspoint.com/python/python_exceptions.htm

**Comment by epeterson12** [comment]
Risky Behavior | Expected Response | Line in code | Notes
------------ | ------------- | ------------- | ------------- 
Load config.yaml | Fail |  |
Load S3 bucket | Fail |  | 
Load S3 bucket | Fail |  | 
Load S3 bucket | Fail |  | 
Load S3 bucket | Fail |  | 
Load S3 bucket | Fail |  | 
Load S3 bucket | Fail |  | 
Load S3 bucket | Fail |  | 
Load S3 bucket | Fail |  | 
Load S3 bucket | Fail |  |

**Comment by epeterson12** [comment]
Expected behaviors should be agreed upon before we change our code to handle exceptions. This is a summary of how I think the program throws an exception during certain actions. Warnings should notify the user that the action couldn't be completed, such as an image not being able to be used for various reasons, then continue running with the rest of the data. Failures should notify the user and terminate the program.

### images_to_samples.py

Risky Behavior | Expected Response | Function | Notes
------------ | ------------- | ------------- | -------------
Load config.yaml | Fail | main() |
Load S3 bucket | Fail | main() |
Get prep.csv from bucket| Fail | main() |
Get prep.csv from local| Fail | main() |
Get images from bucket | Warn | main() |
Get images from local | Warn | main() |
Create temp h5py files | Fail | main() |
Get shp file from bucket| Fail | main() |
Get shp file from local| Fail | main() |
Assert band number| Warn | main() |
Create shp raster image | Warn | main() |
Validate num classes | Warn | main() |
Read images and mask | Warn | main() |
Create shp raster image | Warn | main() |
Create masked raster | Warn | main() |
Create h5py files | Fail | main() |
Delete temp label tif| Warn | main() |
Delete temp hdf5 files | Warn | main() |
Add samples to the bucket | Fail | main() |
Add labels to bucket | Warn | main() |
Delete files downloaded from S3 bucket | Warn | main() |

### train_model.py

Risky Behavior | Expected Response | Function | Notes
------------ | ------------- | ------------- |  -------------
Load config.yaml | Fail | main() |
Load S3 bucket | Fail | main() |
Load samples from bucket| Fail | main() |
Create dataloaders | Fail | main() |
Save intermediate checkpoint | Fail | main() |
Save final Checkpoint | Fail | main() |
Write model to bucket | Fail | main() |
Check trn sample count| Fail | verify_sample_count() |
Check val sample count| Fail | verify_sample_count() |
Metrics logger| Warn | train() |
Metrics logger | Warn | validation() |

### image_classification.py

Risky Behavior | Expected Response | Function | Notes
------------ | ------------- | ------------- | -------------
Load config.yaml | Fail | main() |
Load S3 bucket | Fail | main() |
Load model from bucket| Fail | main() |
Load images to classify from bucket| Warn | main() |
Assert Band number| Warn | main() |
Read image as array | Warn | classification() |
Create new raster from base | Warn | classification() |

**Comment by epeterson12** [comment]
After discussion with ymoisan, we should set a limit to the number of warnings that we give. Once the threshold has been exceeded, the program should throw an exception and terminate. We would do this in case of systematic user error, for example trying to load images only in pdf format or having a different band number or number of classes in the config.yaml compared to the images in use.

**Comment by mpelchat04** [comment]
Relevant exceptions are being implemented ad hoc.
