### ISSUE TITLE
[bug] tiling: empty dataloader but valid gpkg

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#417]
Not a priority. A limit case has caused trouble at tiling:
Imagery: https://datacube-stage.services.geo.ca/api/collections/worldview-3-ortho-pansharp/items/BC37-013904302200_01_P001-WV03
Ground truth (building): buil_BC37-WV03-20150806-1.gpkg

Ground truth contains only 2 buildings:
![image](https://user-images.githubusercontent.com/34774759/206256272-a1e9ab00-159a-4473-9251-be7e4bb836ed.png)
within its entire 113 km2 of imagery:
![2022_12_07_12_49_18_Window](https://user-images.githubusercontent.com/34774759/206257093-8dbc6234-6133-4965-b5bf-cbba6c878aed.png)

Therefore, AOI creation doesn't fail (see: #390) and tiling shouldn't fail either, but it does with the following stack trace:
```
Traceback (most recent call last):
  File "/fs/vnas_Hnrcan/geobase/ret000/geo-deep-learning/GDL.py", line 62, in run_gdl
    task(cfg)
  File "/fs/vnas_Hnrcan/geobase/ret000/geo-deep-learning/tiling_segmentation.py", line 675, in main
    tiler_pair = tiler.tiling_per_aoi(
  File "/fs/vnas_Hnrcan/geobase/ret000/geo-deep-learning/tiling_segmentation.py", line 329, in tiling_per_aoi
    assert len(dataloader) != 0, f"The dataloader is empty for AOI {aoi.aoi_id}. Check input image and vector datasets."
AssertionError: The dataloader is empty for AOI BC37-013904302200_01_P001-WV03. Check input image and vector datasets.
```

**Comment by ms888ekb** [comment]
checked the issue, works on my side, all these tiny houses were tiled.

**Comment by remtav** [comment]
Turns out the dataloader was empty because patch size defined in dataloader (via GridGeoSampler) was larger than the total extent of area to tile from (approx. 60 x 60 pixels). This is not a bug.

The following was tested and succeeded:
python .\GDL.py mode=tiling dataset.raw_data_csv="tests/data/tiling_issue/BC37.csv"

However, adding "tiling.patch_size=512" fails.

**Comment by remtav** [comment]
Turns out the dataloader was empty because patch size defined in dataloader (via GridGeoSampler) was larger than the total extent of area to tile from (approx. 60 x 60 pixels). This is not a bug.

The following was tested and succeeded:
python .\GDL.py mode=tiling dataset.raw_data_csv="tests/data/tiling_issue/BC37.csv"

However, adding "tiling.patch_size=512" fails.
