### ISSUE TITLE
Pytorch 0.4.1 - Upsampling deprecated

### ISSUE THREAD

**Issue by mpelchat04** [NRCan/geo-deep-learning#42]
As of Pytorch 0.4.1, the [upsampling](https://pytorch.org/docs/0.4.1/nn.html#torch.nn.Upsample) function is deprecated, in favor of [interpolate](https://pytorch.org/docs/0.4.1/nn.html?highlight=interpolate#torch.nn.functional.interpolate).
We need to change that in the models.

**Comment by epeterson12** [comment]
There isn't an Interpolate module in pytorch so we will have to create one like in this [pytorch forum post](https://discuss.pytorch.org/t/using-nn-function-interpolate-inside-nn-sequential/23588) using the functional version of interpolate in order to keep this step in our unet models.

**Comment by ymoisan** [comment]
Done with v1.0
