### ISSUE TITLE
state_dict in inference_segmentation.py is different from state_dict in evaluate_segmentation.py

### ISSUE THREAD

**Issue by Ling-Jun** [NRCan/geo-deep-learning#475]
In inference_segmentaion.py, we have: 
state_dict = get_key_def('state_dict_path', params['inference'], to_path=True, validate_path_exists=True,  wildcard='*pth.tar')

In evaluate_segmentation.py, we have:
state_dict = get_key_def('state_dict_path', params['inference'], to_path=True, validate_path_exists=True)

this would fail the evaluation_segmentation task.

**Comment by CharlesAuthier** [comment]
DO you use inference_segmentation.py inside a Docker image?

**Comment by Ling-Jun** [comment]
nope, just ran it directly by python GDL.py mode=inference
