### ISSUE TITLE
environment.yml: conda installing pytorch-cpu even when gpu is available

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#490]
Conda environments built from our environment.yml install a cpu version of pytorch even on machines with GPU.
See issue: https://stackoverflow.com/questions/74234628/new-mamba-environment-force-torch-cpu-and-i-dont-know-why
One solution (tested and works) seems to fix pytorch to 1.12. 
We could also add `pytorch-cuda=11.6` but this would make cpu installs larger. I'd go for fixing pytorch to 1.12, considering 1.13.1 doesn't have [that much more to offer](https://github.com/pytorch/pytorch/releases) for us.

**Comment by Ling-Jun** [comment]
Even with pytorch==1.12, torch still fails to discover my GPU
![image](https://user-images.githubusercontent.com/30609542/221908209-aaf02f4d-a7ad-4dcc-aa6e-d8468a1d6f4b.png)

**Comment by Ling-Jun** [comment]
![image](https://user-images.githubusercontent.com/30609542/221910116-51fa15d4-205c-43b9-a056-7f2b665e2e41.png)

**Comment by Ling-Jun** [comment]
@CharlesAuthier

**Comment by CharlesAuthier** [comment]
So the solution is to recreate the environment and not just update it.
