### ISSUE TITLE
Empty Dataloader

### ISSUE THREAD

**Issue by Abdielfer** [NRCan/geo-deep-learning#510]
As we discussed earlier, here is one of the "issues" I found while tiling.:  " ValueError: The dataloader is empty. Check input image and vector datasets" See the attachment for full error message. 
The points for me are:
1-  Can we be more precise about which file has the problem?
2- Can we report the error and continue tiling the next file if still in something in the list?

**Comment by mpelchat04** [comment]
@Abdielfer  ` See the attachment for full error message.`   
There is no attachement. Could you provide the complete stack trace?

**Comment by Abdielfer** [comment]
[IssueDataloaderEmpty.txt](https://github.com/NRCan/geo-deep-learning/files/11517308/IssueDataloaderEmpty.txt)
