### ISSUE TITLE
add PR template

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#514]
A PR template would ensure contributors follow a uniform procedure when opening PRs
[PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
[Example](https://github.com/CosmiQ/solaris/blob/main/PULL_REQUEST_TEMPLATE.md)

**Comment by valhassan** [comment]
Another example: https://www.talater.com/open-source-templates/#/page/1

**Comment by LucaRom** [comment]
> Another example: https://www.talater.com/open-source-templates/#/page/1

I enjoyed the adventure!
