### ISSUE TITLE
"sqlite3_open" error whith geopackage

### ISSUE THREAD

**Issue by mpelchat04** [NRCan/geo-deep-learning#52]
The error occur in [images_to_samples.py](https://github.com/NRCan/geo-deep-learning/blob/master/images_to_samples.py#L209), when we have more than 1000 images to prepare.  
```shell
...  
Images/mtq_f09_257000_5077000_50_int_rou_asp_slo.tif
{'trn': 42601, 'val': 12404}
Images/15_2525134f09_dc_50_int_rou_asp_slo.tif
{'trn': 42601, 'val': 12501}ERROR 4: sqlite3_open(chapeau_mtm09_lac_riv_build.gpkg) failed: unable to open database file

Images/mtq_f09_260000_5081000_50_int_rou_asp_slo.tif
{'trn': 42601, 'val': 12516}
Images/15_2495160f09_dc_45_50_int_rou_asp_slo.tif
{'trn': 42601, 'val': 12714}
Images/15_2575131f09_dc_50_int_rou_asp_slo.tif
{'trn': 42601, 'val': 12714}
Images/15_2605131f09_dc_50_int_rou_asp_slo.tif
{'trn': 42601, 'val': 12756}
Images/15_2455150f09_dc_50_int_rou_asp_slo.tif
{'trn': 42601, 'val': 12793}
Images/mtq_f09_262000_5093000_50_int_rou_asp_slo.tif
{'trn': 42601, 'val': 12799}
Images/15_2715113f09_dc_50_int_rou_asp_slo.tif
{'trn': 42601, 'val': 12854}
Images/15_2505138f09_dc_50_int_rou_asp_slo.tif
{'trn': 42601, 'val': 12858}
Images/15_2595126f09_dc_50_int_rou_asp_slo.tif
{'trn': 42601, 'val': 12888}
Traceback (most recent call last):
  File "images_to_samples.py", line 258, in <module>
    params['sample']['mask_reference'])
  File "images_to_samples.py", line 209, in main
    vector_to_raster(info['gpkg'], info['attribute_name'], label_raster)
  File "images_to_samples.py", line 133, in vector_to_raster
    source_layer = source_ds.GetLayer()
AttributeError: 'NoneType' object has no attribute 'GetLayer'
```  
One of the possible solutions might include:  
- Using [Fiona](https://fiona.readthedocs.io/en/latest/README.html) to read/write geopackages : Fiona is OGR’s neat and nimble API for Python programmers.  
- Using [Rasterio](https://rasterio.readthedocs.io/en/latest/) for raster read/write : Rasterio reads and writes geospatial raster datasets

**Comment by ymoisan** [comment]
Could Python generators be useful here ?

**Comment by Dan-Eli** [comment]
The following was tested on Windows 10 using Anaconda with conda activating fiona and gdal

Using [Fiona](https://fiona.readthedocs.io/en/latest/README.html) and [Rasterio](https://rasterio.readthedocs.io/en/latest/) are good alternative to direct use of OGR and GDAL as described in [image_to_samples.py](https://github.com/NRCan/geo-deep-learning/blob/master/images_to_samples.py#L209) in the preceding comment.

I tested a prototype using Fiona and Rasterio to read  a GeoPackage file containing 500 000 vector features and for each feature reading a portion of a GeoTIFF file using Rasterio and it works well.

I found one problem when creating the GPKG file with Fiona it exits with the following message
```
ERROR 1: sqlite3_exec(CREATE VIRTUAL TABLE "rtree_line_geom" USING rtree(id, minx, maxx, miny, maxy)) failed: table "rtree_line_geom" already exists
Traceback (most recent call last):
  File "fiona/_err.pyx", line 201, in fiona._err.GDALErrCtxManager.__exit__
fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE "rtree_line_geom" USING rtree(id, minx, maxx, miny, maxy)) failed: table "rtree_line_geom" already exists'
Exception ignored in: 'fiona._shim.gdal_flush_cache'
Traceback (most recent call last):
  File "fiona/_err.pyx", line 201, in fiona._err.GDALErrCtxManager.__exit__
fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE "rtree_line_geom" USING rtree(id, minx, maxx, miny, maxy)) failed: table "rtree_line_geom" already exists'

Process finished with exit code 0
``` 

It's not an error as the Process exit with code  0 and it said in the message Exception ignored.  The GPKG file seems to be created correctly.

As reported [here](https://github.com/conda-forge/fiona-feedstock/issues/53) by @sgillies "This has nothing to do with fiona or the rtree python package. See section 2 of https://www.sqlite.org/rtree.html."

Two options for this issus:
- In anadonda I tested installing Fiona and GDAL manually (pip install...) and it's working and it works without any Traceback
- Make a request  to Anaconda project to modify fiona sqlite product to activate the SQLite with the rtree activated.

The second avenue (request to Anaconda) should be the prefered choice.

**Comment by FelixBuehler** [comment]
> * In anadonda installing Fiona and GDAL manually the wheel (pip install...) and it works without any Traceback

Can anyone tell, how exactly this would work? Download the corresponding .whl files from https://www.lfd.uci.edu/~gohlke/pythonlibs/ and then install them using pip install?

Does any step needs to be done before/after any other step?

**Comment by ymoisan** [comment]
@FelixBuehler : I don't think we have that issue anymore.  The CI [configuration file](https://github.com/NRCan/geo-deep-learning/blob/4cca1dc519c954a885d5a541adf0ee2e0d431124/.travis.yml#L13) shows a clean install and we know it works or else CI would fail.  Did you try a normal conda install ?

**Comment by FelixBuehler** [comment]
@ymoisan I installed geopandas on a clean Anaconda Navigator installation via the environment tab. But I still get the error and the CRS in the GPKG won't be set correctly.


```
Traceback (most recent call last):

  File "fiona/_err.pyx", line 201, in fiona._err.GDALErrCtxManager.__exit__

CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE "rtree_nextbike_geom" USING rtree(id, minx, maxx, miny, maxy)) failed: table "rtree_nextbike_geom" already exists'

Exception ignored in: 'fiona._shim.gdal_flush_cache'
Traceback (most recent call last):
  File "fiona/_err.pyx", line 201, in fiona._err.GDALErrCtxManager.__exit__
fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE "rtree_nextbike_geom" USING rtree(id, minx, maxx, miny, maxy)) failed: table "rtree_nextbike_geom" already exists'
```

**Comment by ymoisan** [comment]
What is the `rtree_nextbike_geom` table ?  Are you trying to install geo-deep-learning ?  

If so, it looks like you've got some environment issues.  I would create a brand new Python 3.6 environment as specified in the CI [configuration file](https://github.com/NRCan/geo-deep-learning/blob/4cca1dc519c954a885d5a541adf0ee2e0d431124/.travis.yml#L13).  If you still have problems, let us know.

**Comment by FelixBuehler** [comment]
> What is the `rtree_nextbike_geom` table ?
I have no idea. nextbike is the name of the layer. It's the same error as @Dan-Eli describes above.
>  Are you trying to install geo-deep-learning ?
Actually no. Just saw it now, that this is about geo-deep-learning. But the post above is the exact same problem as mine.

**Comment by ymoisan** [comment]
DanEli bypassed the conda packaging problem by doing what he describes above : create a "vanilla" conda environment with Python 3.7 and manually install the wheel files and make sure they're on the path.  

We have not tested with more recent versions of conda and/or Fiona so maybe the issue is fixed now but if it's not you'll have to manually install stuff.  Sorry we can't be more helpful.  If you do find how to set this up nice and clean, please let us know.

Good luck
