### ISSUE TITLE
BUG: Version Issue

### ISSUE THREAD

**Issue by Hi-Chem246** [NRCan/geo-deep-learning#551]
**Description**
An import error arises when attempting to run the code. 

"ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/anaconda3/envs/geo_deep_env/lib/python3.10/site-packages/pandas/_libs/window/aggregations.cpython-310-x86_64-linux-gnu.so)"

**Steps To Reproduce**
1. Clone the repository
2. cd geo-deep-learning
3. conda env create -f environment.yml
4. Wait for environment to finish installing 
5. conda activate geo_deep_env
6. python GDL.py mode=training (or tiling or inference)

**Expected behavior**
The code should run without issue. 

**Environment Details**
- Operating System: Ubuntu 20.04.6 LTS
- Conda Version: 22.9.0

**Comment by LucaRom** [comment]
Hi,

I had the same problem and it was solved by exporting the library path of the current Conda environment :

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/`

**Comment by mpelchat04** [comment]
It seems linked to the pandas library. If @LucaRom solution doesn't work, you can try to reinstall the package from your environment.   
```
conda remove pandas
conda install pandas -c conda-forge
```

**Comment by mpelchat04** [comment]
@Hi-Chem246  I'm closing the issue, let us know if our solution did not help you.
