### ISSUE TITLE
Add classification capacity

### ISSUE THREAD

**Issue by ymoisan** [NRCan/geo-deep-learning#6]
#Objectives

The intent of this project is to provide a basic system for deep learning uses in remote sensing (RS). As of today, the application has the capacity to perform semantic segmentation of images. In order to provide a larger capacity for RS tools, there is (at least) one task we need to add to the system : classification.

The definition of both these tasks and the difference between the two can be found in the [lexicon](https://gccode.ssc-spc.gc.ca/cccot-shbk/AP/wikis/documentation/lexicon).

**Comment by epeterson12** [comment]
There seem to be a few main ways that labels are associated with images for classification purposes: 

1.  A relational-db-like structure  using csv or text files ([WordNet](https://wordnet.princeton.edu/), [DeepSat SAT6](https://www.kaggle.com/crawford/deepsat-sat6/home), [Overhead Imagery Research Data Set,](https://sourceforge.net/projects/oirds/) [OpenImages](https://storage.googleapis.com/openimages/web/index.html))
2.  A file system tree ([ImageNet](http://image-net.org/index), [Caltech 101](http://www.vision.caltech.edu/Image_Datasets/Caltech101/))
3.  A custom file format ([MNIST](http://yann.lecun.com/exdb/mnist/))
4.  Pre-made datasets ([CIFAR10 and CIFAR100](https://www.cs.toronto.edu/~kriz/cifar.html))

In pytorch, there is a useful generic dataset class called [ImageFolder](https://pytorch.org/docs/stable/torchvision/datasets.html#imagefolder).  The data must be stored in a file system tree structure like ImageNet. I suggest that we take advantage of this for our classification feature. We would be able to skip the create_samples.py step when doing classification if we use this class.

For our net, we could use an existing net model from Torchvision such as a ResNet or inception3 which both are good for classification. I will be looking in to what needs to be changed in our existing code to add a classification feature using these methods.
