### ISSUE TITLE
Spark/PyTorch integration

### ISSUE THREAD

**Issue by ymoisan** [NRCan/geo-deep-learning#7]
It would be interesting to see how PyTorch can be integrated in the CCMEO big data architecture deployed on AWS.

**Comment by epeterson12** [comment]
We should evaluate whether it it better to just use EC2 instances on AWS or to use SageMaker which[ supports PyTorch](https://aws.amazon.com/blogs/machine-learning/amazon-sagemaker-now-supports-pytorch-and-tensorflow-1-8/). In both cases we can use Spark or directly take the data from an S3 bucket.

**Comment by victorlazio109** [comment]
This has consistently gone down in-order of priority. I would be closing this issue.
