### ISSUE TITLE
Loading pretrained model with different number of classes

### ISSUE THREAD

**Issue by mpelchat04** [NRCan/geo-deep-learning#81]
The actual behavior of GDL doesn't support the modification of an architecture, when loading pretrained weights. So one can not use a pretrained model with 4 classes for prediction and import it for his/her new training on 3 classes for prediction.
We could benefit from a loading process in 3 steps:  
1. loading original model  
2. loading of the weights  
3. modification of the architecture

**Comment by mpelchat04** [comment]
https://pytorch.org/tutorials/beginner/saving_loading_models.html#warmstarting-model-using-parameters-from-a-different-model

**Comment by mpelchat04** [comment]
When loading model from pretrained state_dict, there are 4 things to consider:  
1- The number of input band might not be the same as the loaded state dict;  
2- The number of output class might not be the same as the loaded state dict;  
3- The state dict is loaded from torchvision (only for deeplabv3 and resnet) or from a local path;  
4- State dict `keys` (a.k.a. the layer's name) are different from one model to another.  

Functions to revise:  
- set_hyperparameters  
- load_from_checkpoint  
- model_choice  
- chop_layer  

Config file definitions to revise:  
- `model` section and their associated parameters;  
- Hyperparameters found in the `training` section.

**Comment by remtav** [comment]
> When loading model from pretrained state_dict, there are 4 things to consider:
> 1- The number of input band might not be the same as the loaded state dict;

Thoughts in the same vein: the number of input band might not be the same as the hardcoded input channels in selected model (ex.: torchvision models all accept only 3 band data). Does it mean we will have to copy standard architectures (ex.: deeplabv3) in our code and adapt them just to be able to use non-3-band data ?

This scenario (ou own adapted implementation) creates a burden on development as new models and updates on existing architectures are published, but I don't see any alternative...

**Comment by mpelchat04** [comment]
Does architecture like deeplabv3 support adaptation on the fly?

**Comment by remtav** [comment]
> Does architecture like deeplabv3 support adaptation on the fly?

To my knowledge, torchvision segmentation models, including deeplabv3 (with resnet backbone), are hardcoded to receive a 3 channel input. We would have to suggest modifications to the code in torchvision and implement models on our side meanwhile. 

Otherwise, some models found on github have a `n_channels` parameter as input, e.g. this implementation of [UNet: semantic segmentation with PyTorch](https://github.com/milesial/Pytorch-UNet/tree/master/unet).
