### ISSUE TITLE
Move to Python 3.7

### ISSUE THREAD

**Issue by ymoisan** [NRCan/geo-deep-learning#94]
The table below shows that Python 3.6 is not developed anymore and that Python 3.8 is coming soon, which suggests GDL should be moving to Python 3.7.

| Python | Initial release | Last bugfix release | Last security release | Comments |
|--------|-------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
| 3.6 | [End 2016](https://www.python.org/dev/peps/pep-0494/#schedule) | **[December 2018](https://www.python.org/dev/peps/pep-0494/#schedule-last-bugfix-release)** | Planned [end 2021](https://www.python.org/dev/peps/pep-0494/#and-beyond-schedule) |  |
| 3.7 | [Mid 2018](https://www.python.org/dev/peps/pep-0537/#schedule) | Planned [mid 2020](https://www.python.org/dev/peps/pep-0537/#schedule-last-bugfix-release) | Planned [mid 2023](https://www.python.org/dev/peps/pep-0537/#and-beyond-schedule) | [Interesting features](https://docs.python.org/3/whatsnew/3.7.html) w/r to 3.6 |
| 3.8 | Planned [Fall 2019](https://www.python.org/dev/peps/pep-0569/#schedule) | Not planned yet | Not planned yet |  |

However, there are potential blockers :

- On the [PyTorch home page](https://pytorch.org/), the highlighted Python version in the "QUICK START LOCALLY" section is 3.6 (as of July 2019).  This does not mean that 3.7 is not supported (it is possible to select 3.7), but not defaulting to 3.7 rings a bell that maybe there are things that still work better with 3.6.
- Versions of GDAL prior to 2.4 did not run on Python 3.7 (in our experience).

**Comment by mpelchat04** [comment]
CI uses Python 3.7.
Fixed in #112
